[package]
name = "netrunner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = ["derive"] }
reqwest = "0.11"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
sitemap = "0.4.1"
tokio = { version = "1.0", features = ["full"] }
texting_robots = "0.2.1"
url = "2.3"